Add two CDs
steverichey/PeriodicTableOfItems pull request #2
Opened 2020-05-29 19:36 UTC by EBusch

2020-05-30 18:02 UTC, steverichey requested changes

2020-05-30 18:02 UTC, steverichey commented on known_items.txt
> +Jagged Little Pill CD
I think this is too specific. I'd like each item to be distinct; can we change both of these to just "compact disc"?

2020-06-01 18:27 UTC, EBusch commented on known_items.txt
> +Jagged Little Pill CD
> I think this is too specific. I'd like each item to be distinct; can we change both of these to just "compact disc"?

Jagged Little Pill is revolutionary and I am not sure I can bend on this one.

2020-06-01 19:47 UTC, steverichey commented on known_items.txt
> +Jagged Little Pill CD
I applaud and respect your commitment to your values. Unfortunately, the Contribution License Agreement does not allow opinionated stances.

2020-07-02 19:22 UTC, closed without merging